name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Write SNK file
        shell: pwsh
        run: |
          $env:SNK_BASE64 -split ' ' -join "`n" | Out-File -Encoding utf8 keypair.snk.base64.txt
          certutil -decode keypair.snk.base64.txt keypair.snk
        env:
          SNK_BASE64: ${{ secrets.SNK_BASE64 }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.407'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
